### ISSUE TITLE
Support flatpak path searching in search menu

### ISSUE THREAD

**Issue by prateekmedia** [jmanc3/winbar#37]
Flatpak path is not searched by the menu, Hence No flatpak apps are visible on start menu or searchable via search.

**Comment by jmanc3** [comment]
@prateekmedia Added support for flatpak desktop files in f5c83f3. Some icons won't work right now because we don't currently search any other place than "/usr/share/icons/", and so therefore, we don't check "/var/lib/flatpak/exports/share/icons" (where flatpak icons are stored). This will be remedied at some later point.
