### ISSUE TITLE
[nice to have] Blur or transparent bar

### ISSUE THREAD

**Issue by prateekmedia** [jmanc3/winbar#46]
I don't know If there is a way to add blur or transparency to the bar, if it is there then I would like to know.

It would also attract most people as this will mostly be featured on linux desktop setup subreddit's.

**Comment by prateekmedia** [comment]
@jmanc3 It is not blurring, I guess cause it's not trnasparent, picom only blurs transparent windows, Can we make winbar transparent?

**Comment by jmanc3** [comment]
@prateekmedia in ~/.config/winbar/winbar.cfg, scroll down to the themes and set  


color_taskbar_background
# colors are in hex format and are ARGB (alpha, red, green, blue)
color_taskbar_background = "#dd101010",
to
color_taskbar_background = "#55101010",

if it

**Comment by prateekmedia** [comment]
Ir works but do I have to set it manually for every property?

**Comment by jmanc3** [comment]
Yes. The properties you're probably most interested in changing (those that change the transparency of the window backgrounds) are typically going to have "_background" in the name.
The following are those that you probably want to change:

> colors are ARGB in HEX as in the first two numbers are the opacity, the next to red, the next two green, and then blue
> color_taskbar_background = "#dd101010",
> color_taskbar_search_bar_default_background = "#fff3f3f3",
> color_taskbar_search_bar_hovered_background = "#ffffffff",
> color_taskbar_search_bar_pressed_background = "#ffffffff",
> color_taskbar_application_icons_background = "#dd474747",
> color_taskbar_attention_background = "#ffffa21d",
> color_systray_background = "#f3282828",
> color_battery_background = "#f31f1f1f",
> color_battery_slider_background = "#ff797979",
> color_wifi_background = "#f31f1f1f",
> color_date_background = "#f31f1f1f",
> color_volume_background = "#f31f1f1f",
> color_apps_background = "#f31f1f1f",
> color_pin_menu_background = "#f31f1f1f",
> color_windows_selector_default_background = "#f3282828",
> color_windows_selector_hovered_background = "#f33d3d3d",
> color_windows_selector_pressed_background = "#f3535353",
> color_search_tab_bar_background = "#f31f1f1f",
> color_search_empty_tab_content_background = "#f32a2a2a",
> color_pinned_icon_editor_background = "#ffffffff",
> color_notification_content_background = "#ff1f1f1f",
> color_notification_title_background = "#ff191919",
> color_action_center_background = "#ff1f1f1f",
> color_action_center_notification_content_background = "#ff282828",
> color_action_center_notification_title_background = "#ff1f1f1f",
> 
I am aware it's pretty annoying to change each one individually. The reason I didn't make it so that they all use one _opacity_ number is because some of the windows really don't look good when they are too transparent (you can't make out the text) so I was pretty conservative when choosing "f3." It really shows on compositors that just do basic transparency. But now that I'm looking at the numbers it's really only the taskbar background ("dd") that's not "f3" like the others. I should probably just have a global variable that can be set that'll apply to everything.
