### ISSUE TITLE
Add retry button or retry automatically in sound menu

### ISSUE THREAD

**Issue by prateekmedia** [jmanc3/winbar#47]
If my pc opens faster then my TV then it doesn't detects the TV audio output and results in "Failed to connect to pulseaudio" error in menu, but if I restart winbar then it connects successfully, so if it retry automatically on sound menu open or it has a retry button then it would be awesome.

**Comment by jmanc3** [comment]
Added this feature in [d1f66c8](https://github.com/jmanc3/winbar/commit/d1f66c8c5695a71a453923249f631917da263e2c), but also made it so that opening the volume menu will automatically retry to establish a connection (if it is not already established, that is) so it should just work automatically now. Let me know.

**Comment by prateekmedia** [comment]
Thank you!
